name: Release Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up GraalVM CE and SBT
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Build project
        run: sbt build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Setup Pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.2
        with:
          pulumi-version: 2.12.0
      - name: Configure Pulumi Credentials
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Deploy Pulumi stack
        run: |
          cd infrastructure
          pulumi stack select production
          pulumi up --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: pulumi
        name: Export Pulumi stack variables
        run: |
          cd infrastructure
          echo ::set-output name=AWS_REGION::$(pulumi config get aws:region)
          pulumi stack output Exports -j | jq --raw-output 'to_entries | map("::set-output name=" + .key+"::" + (.value | tostring)+"^") | .[]' | xargs -d '^' echo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ steps.pulumi.outputs.AWS_REGION }}
      - name: Upload site to AWS S3
        run: |
          aws s3 sync site/build s3://${{ steps.pulumi.outputs.contentBucketUri }} --no-progress --follow-symlinks --delete --cache-control 'public, max-age=2628000'
      - name: Invalidate AWS Cloudfront distribution cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.pulumi.outputs.cloudFrontId }} --paths "/*"